apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
  namespace: ratelimit
data:
  config.yaml: |
    domain: carsharing-edge
    descriptors:
      - key: remote_address
        rate_limit:
          unit: second
          requests_per_unit: 200
      - key: header_match
        value: "trip_start"
        descriptors:
          - key: user_id
            rate_limit:
              unit: second
              requests_per_unit: 5
      - key: user_id
        rate_limit:
          unit: second
          requests_per_unit: 60
